import { PrismaClient } from '@prisma/client'
import * as bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Iniciando seed...')

  // Cidades
  const fortaleza = await prisma.cidade.upsert({
    where: { slug: 'fortaleza' },
    update: {},
    create: { nome: 'Fortaleza', slug: 'fortaleza', estado: 'CE', regiao: 'Região Metropolitana de Fortaleza' },
  })
  const caucaia = await prisma.cidade.upsert({
    where: { slug: 'caucaia' },
    update: {},
    create: { nome: 'Caucaia', slug: 'caucaia', estado: 'CE', regiao: 'Região Metropolitana de Fortaleza' },
  })
  const maracanau = await prisma.cidade.upsert({
    where: { slug: 'maracanau' },
    update: {},
    create: { nome: 'Maracanaú', slug: 'maracanau', estado: 'CE', regiao: 'Região Metropolitana de Fortaleza' },
  })
  const eusebio = await prisma.cidade.upsert({
    where: { slug: 'eusebio' },
    update: {},
    create: { nome: 'Eusébio', slug: 'eusebio', estado: 'CE', regiao: 'Região Metropolitana de Fortaleza' },
  })
  await prisma.cidade.upsert({
    where: { slug: 'aquiraz' },
    update: {},
    create: { nome: 'Aquiraz', slug: 'aquiraz', estado: 'CE', regiao: 'Região Metropolitana de Fortaleza' },
  })
  console.log('✅ Cidades criadas')

  // Bairros de Fortaleza
  const bairrosData = [
    {
      nome: 'Meireles',
      slug: 'meireles',
      regiao: 'Zona Leste',
      perfil: 'ALTO_PADRAO' as const,
      precoM2MedioVenda: 9500,
      precoM2MedioLocacao: 42,
      valorizacao12meses: 8.0,
      pontuacaoInfraestrutura: 95,
      descricaoSeo: 'O Meireles é o bairro mais valorizado de Fortaleza, localizado à beira-mar na Zona Leste. Referência em alto padrão, o bairro concentra os melhores restaurantes, hotéis e opções de lazer da cidade. Com excelente infraestrutura, acesso à Beira Mar e perfil cosmopolita, é a escolha preferida de famílias e investidores que buscam qualidade de vida no litoral cearense.',
      infraestrutura: {
        escolas: ['Colégio Christus', 'Colégio Farias Brito', 'Colégio Dom Bosco'],
        hospitais: ['Hospital do Coração', 'Unimed Fortaleza', 'Hospital Geral de Fortaleza'],
        shoppings: ['Shopping Aldeota', 'RioMar Fortaleza'],
        transporte: ['BRT Av. Abolição', 'Diversas linhas de ônibus', 'Ciclovia Beira Mar'],
      },
      imagemDestaqueUrl: '[FOTO_MEIRELES_A_DEFINIR]',
      metaTitle: 'Imóveis no Meireles, Fortaleza — Comprar e Alugar | IMOV Imobiliária',
      metaDescription: 'Encontre apartamentos, coberturas e casas no Meireles, o bairro mais valorizado de Fortaleza. Preço médio R$ 9.500/m². Ver ofertas disponíveis.',
    },
    {
      nome: 'Aldeota',
      slug: 'aldeota',
      regiao: 'Zona Leste',
      perfil: 'ALTO_PADRAO' as const,
      precoM2MedioVenda: 8200,
      precoM2MedioLocacao: 36,
      valorizacao12meses: 6.0,
      pontuacaoInfraestrutura: 92,
      descricaoSeo: 'A Aldeota é um dos bairros mais tradicionais e valorizados de Fortaleza. Localizada na Zona Leste, é conhecida pela concentração de consultórios médicos, escritórios e comércio sofisticado. Com excelente infraestrutura de serviços, escolas renomadas e fácil acesso a toda a cidade, a Aldeota é uma das regiões mais procuradas por profissionais liberais e famílias de alto padrão.',
      infraestrutura: {
        escolas: ['Colégio Christus Aldeota', 'Colégio Farias Brito', 'UNIFOR'],
        hospitais: ['Hospital Batista Memorial', 'Hospital São Camilo', 'Clínica São Raimundo'],
        shoppings: ['Shopping Aldeota', 'North Shopping'],
        transporte: ['Metrô Linha Sul', 'BRT Av. 13 de Maio', 'Diversas linhas de ônibus'],
      },
      imagemDestaqueUrl: '[FOTO_ALDEOTA_A_DEFINIR]',
      metaTitle: 'Imóveis na Aldeota, Fortaleza — Comprar e Alugar | IMOV Imobiliária',
      metaDescription: 'Apartamentos e coberturas na Aldeota, bairro tradicional e valorizado de Fortaleza. Preço médio R$ 8.200/m². Consulte as melhores ofertas.',
    },
    {
      nome: 'Cocó',
      slug: 'coco',
      regiao: 'Zona Leste',
      perfil: 'ALTO_PADRAO' as const,
      precoM2MedioVenda: 9800,
      precoM2MedioLocacao: 44,
      valorizacao12meses: 9.0,
      pontuacaoInfraestrutura: 93,
      descricaoSeo: 'O Cocó é um dos bairros com maior valorização de Fortaleza, vizinho ao Parque Ecológico do Cocó — maior parque urbano do Brasil. Referência em qualidade de vida, o bairro une natureza e modernidade, com condomínios de alto padrão, excelente infraestrutura e fácil acesso ao Iguatemi e ao Centro Empresarial. Ideal para famílias que valorizam verde, esporte e segurança.',
      infraestrutura: {
        escolas: ['Escola José de Anchieta', 'Colégio Ari de Sá', 'Universidade de Fortaleza'],
        hospitais: ['Hospital Hapvida', 'UPA Messejana', 'Clínica Cirúrgica do Ceará'],
        shoppings: ['Shopping Iguatemi', 'Shopping RioMar Kennedy'],
        transporte: ['Av. Washington Soares', 'Diversas linhas de ônibus', 'Ciclovia do Parque do Cocó'],
      },
      imagemDestaqueUrl: '[FOTO_COCO_A_DEFINIR]',
      metaTitle: 'Imóveis no Cocó, Fortaleza — Comprar e Alugar | IMOV Imobiliária',
      metaDescription: 'Imóveis no Cocó, bairro com maior valorização em Fortaleza. Próximo ao Parque do Cocó. Preço médio R$ 9.800/m². Ver opções disponíveis.',
    },
    {
      nome: 'Fátima',
      slug: 'fatima',
      regiao: 'Zona Sudoeste',
      perfil: 'MEDIO' as const,
      precoM2MedioVenda: 5500,
      precoM2MedioLocacao: 22,
      valorizacao12meses: 4.0,
      pontuacaoInfraestrutura: 78,
      descricaoSeo: 'O bairro Fátima é uma das regiões mais tradicionais e consolidadas de Fortaleza. Com perfil residencial e boa infraestrutura urbana, oferece opções para famílias que buscam qualidade de vida a preços mais acessíveis que os bairros nobre da Zona Leste. Bem servido de transporte público, comércio local e escolas de qualidade.',
      infraestrutura: {
        escolas: ['Colégio Nossa Senhora de Fátima', 'Escola Estadual Fátima', 'CETREDE'],
        hospitais: ['UPA Fátima', 'Hospital Regional'],
        shoppings: ['Iguatemi Fortaleza (próximo)', 'Centro de Fortaleza'],
        transporte: ['Metrô Linha Sul - Estação Parangaba', 'Diversas linhas de ônibus'],
      },
      imagemDestaqueUrl: '[FOTO_FATIMA_A_DEFINIR]',
      metaTitle: 'Imóveis no Fátima, Fortaleza — Comprar e Alugar | IMOV Imobiliária',
      metaDescription: 'Apartamentos e casas no bairro Fátima, Fortaleza. Bairro tradicional com boa infraestrutura. Preço médio R$ 5.500/m². Confira as opções.',
    },
    {
      nome: 'Parangaba',
      slug: 'parangaba',
      regiao: 'Zona Sudoeste',
      perfil: 'MEDIO' as const,
      precoM2MedioVenda: 4200,
      precoM2MedioLocacao: 18,
      valorizacao12meses: 3.0,
      pontuacaoInfraestrutura: 70,
      descricaoSeo: 'A Parangaba é um bairro central de Fortaleza, conhecido pelo hub do metrô que integra as linhas Sul e Oeste. Com crescente investimento em infraestrutura e localização estratégica, o bairro tem atraído novos empreendimentos imobiliários. Boa opção para quem busca imóveis com preços acessíveis e fácil mobilidade urbana.',
      infraestrutura: {
        escolas: ['EEEP Parangaba', 'Escola Estadual Clóvis Beviláqua', 'SENAC CE'],
        hospitais: ['Hospital Geral de Fortaleza (próximo)', 'UPA Parangaba'],
        shoppings: ['Shopping Parangaba', 'Centro de Fortaleza'],
        transporte: ['Metrô Parangaba (integração linhas Sul e Oeste)', 'Terminal Parangaba', 'Diversas linhas de ônibus'],
      },
      imagemDestaqueUrl: '[FOTO_PARANGABA_A_DEFINIR]',
      metaTitle: 'Imóveis na Parangaba, Fortaleza — Comprar e Alugar | IMOV Imobiliária',
      metaDescription: 'Imóveis na Parangaba, bairro central de Fortaleza com metrô. Preço médio R$ 4.200/m². Boa opção com excelente mobilidade urbana.',
    },
    {
      nome: 'Benfica',
      slug: 'benfica',
      regiao: 'Zona Centro',
      perfil: 'MEDIO' as const,
      precoM2MedioVenda: 4800,
      precoM2MedioLocacao: 20,
      valorizacao12meses: 4.0,
      pontuacaoInfraestrutura: 75,
      descricaoSeo: 'O Benfica é um bairro universitário por excelência em Fortaleza, sede da UFC e UECE. Dinâmico e vibrante, combina o movimento acadêmico com comércio variado e boa infraestrutura de serviços. Excelente opção para investidores que buscam imóveis para locação universitária ou estudantes em busca de moradia próxima às principais universidades cearenses.',
      infraestrutura: {
        escolas: ['UFC - Campus Benfica', 'UECE', 'Instituto Federal do Ceará'],
        hospitais: ['Hospital Universitário Walter Cantídio', 'Hospital de Saúde Mental'],
        shoppings: ['Via Sul Shopping', 'Centro de Fortaleza'],
        transporte: ['Metrô Benfica', 'Terminal Benfica', 'Diversas linhas de ônibus'],
      },
      imagemDestaqueUrl: '[FOTO_BENFICA_A_DEFINIR]',
      metaTitle: 'Imóveis no Benfica, Fortaleza — Comprar e Alugar | IMOV Imobiliária',
      metaDescription: 'Apartamentos e kitinetes no Benfica, bairro universitário de Fortaleza. Próximo à UFC e UECE. Preço médio R$ 4.800/m². Ver ofertas.',
    },
    {
      nome: 'Edson Queiroz',
      slug: 'edson-queiroz',
      regiao: 'Zona Leste',
      perfil: 'ALTO_PADRAO' as const,
      precoM2MedioVenda: 7200,
      precoM2MedioLocacao: 32,
      valorizacao12meses: 7.0,
      pontuacaoInfraestrutura: 85,
      descricaoSeo: 'Edson Queiroz é uma das regiões com maior crescimento imobiliário de Fortaleza. Sede da UNIFOR e do complexo empresarial da cidade, o bairro combina modernidade, infraestrutura de ponta e localização privilegiada no corredor da Av. Washington Soares. Condomínios fechados, shoppings e centros médicos fazem do Edson Queiroz uma das regiões mais completas de Fortaleza.',
      infraestrutura: {
        escolas: ['UNIFOR', 'Colégio Ari de Sá', 'Colégio Monteiro Lobato'],
        hospitais: ['Hospital Universitário da UNIFOR', 'Hapvida Diagnósticos'],
        shoppings: ['Shopping Iguatemi', 'Shopping RioMar Kennedy'],
        transporte: ['Av. Washington Soares', 'Diversas linhas de ônibus'],
      },
      imagemDestaqueUrl: '[FOTO_EDSON_QUEIROZ_A_DEFINIR]',
      metaTitle: 'Imóveis no Edson Queiroz, Fortaleza — Comprar e Alugar | IMOV',
      metaDescription: 'Imóveis no Edson Queiroz, área em crescimento de Fortaleza. Próximo à UNIFOR e Iguatemi. Preço médio R$ 7.200/m². Consulte as opções.',
    },
    {
      nome: 'Messejana',
      slug: 'messejana',
      regiao: 'Zona Sul',
      perfil: 'POPULAR' as const,
      precoM2MedioVenda: 3500,
      precoM2MedioLocacao: 15,
      valorizacao12meses: 3.0,
      pontuacaoInfraestrutura: 60,
      descricaoSeo: 'A Messejana é um dos maiores e mais populosos bairros de Fortaleza, localizado na Zona Sul. Com infraestrutura consolidada, fácil acesso à BR-116 e ao Anel Viário, o bairro oferece imóveis com excelente custo-benefício. Boa opção para famílias que buscam espaço, praticidade e preços acessíveis a poucos quilômetros do centro.',
      infraestrutura: {
        escolas: ['EEFM Messejana', 'Escola Estadual Augusto Severo', 'Instituto Dom Bosco'],
        hospitais: ['UPA Messejana', 'Hospital Distrital Gonzaga Mota'],
        shoppings: ['Via Sul Shopping', 'Fortaleza Shopping'],
        transporte: ['Terminal Messejana', 'BRT Av. Paulino Rocha', 'Diversas linhas de ônibus'],
      },
      imagemDestaqueUrl: '[FOTO_MESSEJANA_A_DEFINIR]',
      metaTitle: 'Imóveis na Messejana, Fortaleza — Comprar e Alugar | IMOV Imobiliária',
      metaDescription: 'Casas e apartamentos na Messejana, Fortaleza. Bairro popular com ótimo custo-benefício. Preço médio R$ 3.500/m². Ver opções disponíveis.',
    },
    {
      nome: 'Maraponga',
      slug: 'maraponga',
      regiao: 'Zona Sudoeste',
      perfil: 'POPULAR' as const,
      precoM2MedioVenda: 3200,
      precoM2MedioLocacao: 14,
      valorizacao12meses: 2.0,
      pontuacaoInfraestrutura: 55,
      descricaoSeo: 'A Maraponga é um bairro residencial popular de Fortaleza, com forte identidade comunitária e bom acesso ao centro da cidade. Oferece imóveis com preços acessíveis e é bem servida de transporte público. Boa opção para primeiro imóvel ou financiamento pelo Minha Casa Minha Vida.',
      infraestrutura: {
        escolas: ['EEFM Maraponga', 'Escola Municipal Maraponga'],
        hospitais: ['UPA Maraponga', 'Posto de Saúde Maraponga'],
        shoppings: ['Shopping Maraponga', 'Centro de Fortaleza'],
        transporte: ['Metrô Linha Oeste', 'Terminal Maraponga', 'Diversas linhas de ônibus'],
      },
      imagemDestaqueUrl: '[FOTO_MARAPONGA_A_DEFINIR]',
      metaTitle: 'Imóveis na Maraponga, Fortaleza — Comprar e Alugar | IMOV Imobiliária',
      metaDescription: 'Apartamentos e casas na Maraponga, Fortaleza. Preços acessíveis, próximo ao metrô. Preço médio R$ 3.200/m². Confira as opções.',
    },
    {
      nome: 'Parquelândia',
      slug: 'parquelandia',
      regiao: 'Zona Norte',
      perfil: 'MEDIO' as const,
      precoM2MedioVenda: 5000,
      precoM2MedioLocacao: 21,
      valorizacao12meses: 4.0,
      pontuacaoInfraestrutura: 72,
      descricaoSeo: 'A Parquelândia é um bairro residencial consolidado na Zona Norte de Fortaleza, com perfil tranquilo e familiar. Bem localizado entre o Centro e o litoral Norte, oferece boa infraestrutura de serviços, escolas e fácil acesso às principais vias da cidade. Opção interessante para famílias que buscam equilíbrio entre localização, qualidade e preço.',
      infraestrutura: {
        escolas: ['Colégio Parquelândia', 'EEFM Parquelândia', 'Centro Universitário Estácio'],
        hospitais: ['Hospital São José', 'UPA Parquelândia'],
        shoppings: ['North Shopping', 'Shopping Conjunto Ceará'],
        transporte: ['Diversas linhas de ônibus', 'Via expressa Norte'],
      },
      imagemDestaqueUrl: '[FOTO_PARQUELANDIA_A_DEFINIR]',
      metaTitle: 'Imóveis na Parquelândia, Fortaleza — Comprar e Alugar | IMOV',
      metaDescription: 'Imóveis na Parquelândia, bairro familiar e tranquilo de Fortaleza. Preço médio R$ 5.000/m². Boa infraestrutura e localização. Ver opções.',
    },
  ]

  const bairros: Record<string, { id: string }> = {}
  for (const b of bairrosData) {
    const bairro = await prisma.bairro.upsert({
      where: { slug: b.slug },
      update: {},
      create: {
        ...b,
        infraestrutura: b.infraestrutura,
        precoM2MedioVenda: b.precoM2MedioVenda,
        precoM2MedioLocacao: b.precoM2MedioLocacao,
        valorizacao12meses: b.valorizacao12meses,
        cidadeId: fortaleza.id,
      },
    })
    bairros[b.slug] = bairro
  }
  console.log('✅ Bairros criados')

  // Imóveis placeholder (dados coerentes com o mercado de Fortaleza)
  const imoveisData = [
    {
      slug: 'apartamento-3-quartos-meireles-beira-mar',
      titulo: 'Apartamento 3 Quartos no Meireles com Vista Mar',
      descricao: '[DADO_REAL_A_IMPORTAR] Apartamento de alto padrão com vista privilegiada para o Mar, localizado a 2 quadras da Beira Mar de Fortaleza. Acabamento premium, varanda gourmet e estrutura de lazer completa.',
      tipo: 'APARTAMENTO' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 1250000,
      precoCondominio: 1800,
      precoIptu: 4200,
      areaTotal: 130,
      areaPrivativa: 110,
      quartos: 3,
      suites: 1,
      banheiros: 2,
      vagas: 2,
      andarPavimento: 12,
      totalAndares: 18,
      anoConstrucao: 2019,
      aceitaFinanciamento: true,
      aceitaFgts: false,
      aceitaConsorcio: false,
      elegivelMcmv: false,
      destaque: true,
      novo: false,
      oportunidade: false,
      rankingScore: 78,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60165-000',
      latitude: -3.7283,
      longitude: -38.4897,
      construtoraNome: null,
      diferenciais: ['Piscina', 'Academia', 'Salão de Festas', 'Portaria 24h', 'Varanda Gourmet', 'Vista Mar'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'meireles',
    },
    {
      slug: 'apartamento-2-quartos-meireles-200m-praia',
      titulo: 'Apartamento 2 Quartos no Meireles, 200m da Praia',
      descricao: '[DADO_REAL_A_IMPORTAR] Apartamento bem localizado no Meireles, a poucos metros da Praia de Iracema. Ideal para moradia ou investimento em locação de temporada.',
      tipo: 'APARTAMENTO' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 680000,
      precoCondominio: 1200,
      precoIptu: 2400,
      areaTotal: 72,
      areaPrivativa: 65,
      quartos: 2,
      suites: 1,
      banheiros: 2,
      vagas: 1,
      andarPavimento: 8,
      totalAndares: 14,
      anoConstrucao: 2021,
      aceitaFinanciamento: true,
      aceitaFgts: false,
      aceitaConsorcio: false,
      elegivelMcmv: false,
      destaque: true,
      novo: false,
      oportunidade: true,
      rankingScore: 85,
      endereco: 'Av. [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60165-120',
      latitude: -3.7290,
      longitude: -38.4920,
      construtoraNome: null,
      diferenciais: ['Piscina', 'Academia', 'Portaria 24h', 'Vaga de Garagem'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'meireles',
    },
    {
      slug: 'cobertura-duplex-aldeota-fortaleza',
      titulo: 'Cobertura Duplex na Aldeota com Piscina Privativa',
      descricao: '[DADO_REAL_A_IMPORTAR] Cobertura duplex de alto padrão na Aldeota com piscina privativa, churrasqueira e vista panorâmica para Fortaleza. Acabamento de primeira linha.',
      tipo: 'COBERTURA' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 2100000,
      precoCondominio: 3500,
      precoIptu: 8000,
      areaTotal: 280,
      areaPrivativa: 240,
      quartos: 4,
      suites: 3,
      banheiros: 5,
      vagas: 4,
      andarPavimento: 18,
      totalAndares: 18,
      anoConstrucao: 2018,
      aceitaFinanciamento: true,
      aceitaFgts: false,
      aceitaConsorcio: true,
      elegivelMcmv: false,
      destaque: true,
      novo: false,
      oportunidade: false,
      rankingScore: 62,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60140-110',
      latitude: -3.7421,
      longitude: -38.4985,
      construtoraNome: null,
      diferenciais: ['Piscina Privativa', 'Churrasqueira', 'Sala de Home Theater', 'Portaria 24h', 'Espaço Gourmet'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'aldeota',
    },
    {
      slug: 'apartamento-3-quartos-coco-parque',
      titulo: 'Apartamento 3 Quartos no Cocó com Vista para o Parque',
      descricao: '[DADO_REAL_A_IMPORTAR] Apartamento moderno no Cocó com vista privilegiada para o Parque Ecológico. Condomínio completo com piscina, academia e playground.',
      tipo: 'APARTAMENTO' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 980000,
      precoCondominio: 1600,
      precoIptu: 3600,
      areaTotal: 105,
      areaPrivativa: 90,
      quartos: 3,
      suites: 2,
      banheiros: 3,
      vagas: 2,
      andarPavimento: 7,
      totalAndares: 12,
      anoConstrucao: 2022,
      aceitaFinanciamento: true,
      aceitaFgts: false,
      aceitaConsorcio: false,
      elegivelMcmv: false,
      destaque: true,
      novo: true,
      oportunidade: true,
      rankingScore: 88,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60192-050',
      latitude: -3.7650,
      longitude: -38.4820,
      construtoraNome: null,
      diferenciais: ['Piscina', 'Academia', 'Playground', 'Portaria 24h', 'Vista para o Parque'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'coco',
    },
    {
      slug: 'casa-condominio-edson-queiroz-3-quartos',
      titulo: 'Casa em Condomínio Fechado no Edson Queiroz, 3 Quartos',
      descricao: '[DADO_REAL_A_IMPORTAR] Casa em condomínio fechado no Edson Queiroz. Excelente padrão construtivo, segurança 24h e área de lazer completa. Próximo à UNIFOR e Shopping Iguatemi.',
      tipo: 'CASA' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 850000,
      precoCondominio: 1400,
      precoIptu: 2800,
      areaTotal: 200,
      areaPrivativa: 160,
      quartos: 3,
      suites: 2,
      banheiros: 3,
      vagas: 3,
      anoConstrucao: 2020,
      aceitaFinanciamento: true,
      aceitaFgts: false,
      aceitaConsorcio: true,
      elegivelMcmv: false,
      destaque: false,
      novo: false,
      oportunidade: true,
      rankingScore: 80,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60811-000',
      latitude: -3.7830,
      longitude: -38.4680,
      construtoraNome: null,
      diferenciais: ['Piscina', 'Área de Lazer', 'Portaria 24h', 'Quintal', 'Espaço Gourmet'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'edson-queiroz',
    },
    {
      slug: 'apartamento-2-quartos-fatima-fortaleza',
      titulo: 'Apartamento 2 Quartos no Bairro Fátima, Fortaleza',
      descricao: '[DADO_REAL_A_IMPORTAR] Apartamento bem conservado no bairro Fátima. Localização central, próximo ao metrô e com fácil acesso a toda Fortaleza. Ótima opção para moradia ou investimento.',
      tipo: 'APARTAMENTO' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 420000,
      precoCondominio: 800,
      precoIptu: 1500,
      areaTotal: 75,
      areaPrivativa: 68,
      quartos: 2,
      suites: 0,
      banheiros: 2,
      vagas: 1,
      andarPavimento: 4,
      totalAndares: 10,
      anoConstrucao: 2015,
      aceitaFinanciamento: true,
      aceitaFgts: true,
      aceitaConsorcio: true,
      elegivelMcmv: false,
      destaque: false,
      novo: false,
      oportunidade: true,
      rankingScore: 76,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60050-000',
      latitude: -3.7560,
      longitude: -38.5210,
      construtoraNome: null,
      diferenciais: ['Portaria 24h', 'Vaga de Garagem', 'Área de Lazer'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'fatima',
    },
    {
      slug: 'apartamento-1-quarto-benfica-universitario',
      titulo: 'Kitnet 1 Quarto no Benfica, Próximo à UFC',
      descricao: '[DADO_REAL_A_IMPORTAR] Kitnet ideal para estudantes universitários, a 5 minutos da UFC e UECE. Localização privilegiada no coração do bairro universitário de Fortaleza.',
      tipo: 'KITNET' as const,
      modalidade: 'LOCACAO' as const,
      status: 'DISPONIVEL' as const,
      preco: 1200,
      precoCondominio: 200,
      precoIptu: 500,
      areaTotal: 30,
      areaPrivativa: 28,
      quartos: 1,
      suites: 0,
      banheiros: 1,
      vagas: 0,
      andarPavimento: 2,
      totalAndares: 6,
      anoConstrucao: 2010,
      aceitaFinanciamento: false,
      aceitaFgts: false,
      aceitaConsorcio: false,
      elegivelMcmv: false,
      destaque: false,
      novo: false,
      oportunidade: true,
      rankingScore: 70,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60430-000',
      latitude: -3.7490,
      longitude: -38.5350,
      construtoraNome: null,
      diferenciais: ['Mobiliado', 'Internet inclusa', 'Próximo ao Metrô'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'benfica',
    },
    {
      slug: 'casa-3-quartos-messejana-fortaleza',
      titulo: 'Casa 3 Quartos na Messejana, Fortaleza',
      descricao: '[DADO_REAL_A_IMPORTAR] Casa espaçosa na Messejana com 3 quartos, quintal e garagem. Ótimo custo-benefício. Acesso fácil à BR-116 e ao Anel Viário de Fortaleza.',
      tipo: 'CASA' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 380000,
      precoCondominio: null,
      precoIptu: 1200,
      areaTotal: 160,
      areaPrivativa: 140,
      quartos: 3,
      suites: 1,
      banheiros: 2,
      vagas: 2,
      anoConstrucao: 2012,
      aceitaFinanciamento: true,
      aceitaFgts: true,
      aceitaConsorcio: true,
      elegivelMcmv: false,
      destaque: false,
      novo: false,
      oportunidade: true,
      rankingScore: 82,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60841-000',
      latitude: -3.8160,
      longitude: -38.5020,
      construtoraNome: null,
      diferenciais: ['Quintal', 'Garagem Coberta', 'Lavanderia', 'Churrasqueira'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'messejana',
    },
    {
      slug: 'apartamento-mcmv-maraponga-2-quartos',
      titulo: 'Apartamento 2 Quartos na Maraponga, Elegível MCMV',
      descricao: '[DADO_REAL_A_IMPORTAR] Apartamento novo elegível para o programa Minha Casa Minha Vida. Localizado na Maraponga, próximo ao metrô. Ótima oportunidade para primeiro imóvel.',
      tipo: 'APARTAMENTO' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 240000,
      precoCondominio: 400,
      precoIptu: 600,
      areaTotal: 50,
      areaPrivativa: 45,
      quartos: 2,
      suites: 0,
      banheiros: 1,
      vagas: 1,
      andarPavimento: 3,
      totalAndares: 8,
      anoConstrucao: 2023,
      aceitaFinanciamento: true,
      aceitaFgts: true,
      aceitaConsorcio: false,
      elegivelMcmv: true,
      destaque: false,
      novo: true,
      oportunidade: true,
      rankingScore: 91,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60710-000',
      latitude: -3.7910,
      longitude: -38.5640,
      construtoraNome: '[DADO_REAL_A_IMPORTAR]',
      diferenciais: ['Novo', 'Minha Casa Minha Vida', 'Próximo ao Metrô', 'Aceita FGTS'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'maraponga',
    },
    {
      slug: 'terreno-parquelandia-fortaleza-500m2',
      titulo: 'Terreno 500m² na Parquelândia, Fortaleza',
      descricao: '[DADO_REAL_A_IMPORTAR] Terreno plano com 500m² em localização privilegiada na Parquelândia. Ideal para construção de casa ou investimento imobiliário. Topografia plana, documentação regular.',
      tipo: 'TERRENO' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 450000,
      precoCondominio: null,
      precoIptu: 1800,
      areaTotal: 500,
      areaPrivativa: null,
      quartos: 0,
      suites: 0,
      banheiros: 0,
      vagas: 0,
      anoConstrucao: null,
      aceitaFinanciamento: true,
      aceitaFgts: false,
      aceitaConsorcio: true,
      elegivelMcmv: false,
      destaque: false,
      novo: false,
      oportunidade: false,
      rankingScore: 55,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60740-000',
      latitude: -3.7290,
      longitude: -38.5810,
      construtoraNome: null,
      diferenciais: ['Terreno Plano', 'Documentação Regular', 'Próximo ao Centro'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'parquelandia',
    },
    {
      slug: 'apartamento-4-quartos-coco-alto-padrao',
      titulo: 'Apartamento 4 Quartos de Alto Padrão no Cocó',
      descricao: '[DADO_REAL_A_IMPORTAR] Apartamento de alto padrão no Cocó com 4 quartos, 3 suítes e 3 vagas de garagem. Condomínio com infraestrutura completa e segurança 24h.',
      tipo: 'APARTAMENTO' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 1850000,
      precoCondominio: 2800,
      precoIptu: 7200,
      areaTotal: 195,
      areaPrivativa: 175,
      quartos: 4,
      suites: 3,
      banheiros: 4,
      vagas: 3,
      andarPavimento: 15,
      totalAndares: 20,
      anoConstrucao: 2020,
      aceitaFinanciamento: true,
      aceitaFgts: false,
      aceitaConsorcio: false,
      elegivelMcmv: false,
      destaque: true,
      novo: false,
      oportunidade: false,
      rankingScore: 68,
      endereco: 'Av. [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60190-000',
      latitude: -3.7640,
      longitude: -38.4790,
      construtoraNome: null,
      diferenciais: ['Piscina', 'Academia', 'Quadra de Tênis', 'Espaço Gourmet', 'Portaria 24h', 'Salão de Festas'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'coco',
    },
    {
      slug: 'apartamento-2-quartos-aldeota-locacao',
      titulo: 'Apartamento 2 Quartos para Alugar na Aldeota',
      descricao: '[DADO_REAL_A_IMPORTAR] Apartamento para locação na Aldeota, excelente localização. Próximo a consultórios, escolas e com fácil acesso ao metrô. Mobiliado.',
      tipo: 'APARTAMENTO' as const,
      modalidade: 'LOCACAO' as const,
      status: 'DISPONIVEL' as const,
      preco: 2800,
      precoCondominio: 900,
      precoIptu: 2400,
      areaTotal: 80,
      areaPrivativa: 72,
      quartos: 2,
      suites: 1,
      banheiros: 2,
      vagas: 1,
      andarPavimento: 6,
      totalAndares: 12,
      anoConstrucao: 2017,
      aceitaFinanciamento: false,
      aceitaFgts: false,
      aceitaConsorcio: false,
      elegivelMcmv: false,
      destaque: false,
      novo: false,
      oportunidade: true,
      rankingScore: 72,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60140-000',
      latitude: -3.7430,
      longitude: -38.4960,
      construtoraNome: null,
      diferenciais: ['Mobiliado', 'Portaria 24h', 'Vaga de Garagem', 'Próximo ao Metrô'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'aldeota',
    },
    {
      slug: 'apartamento-3-quartos-parangaba-fortaleza',
      titulo: 'Apartamento 3 Quartos na Parangaba, Próximo ao Metrô',
      descricao: '[DADO_REAL_A_IMPORTAR] Apartamento bem localizado na Parangaba, próximo ao hub do metrô. Boa opção para moradia ou investimento em locação. Aceita FGTS e financiamento.',
      tipo: 'APARTAMENTO' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 320000,
      precoCondominio: 600,
      precoIptu: 1000,
      areaTotal: 70,
      areaPrivativa: 63,
      quartos: 3,
      suites: 0,
      banheiros: 2,
      vagas: 1,
      andarPavimento: 5,
      totalAndares: 10,
      anoConstrucao: 2016,
      aceitaFinanciamento: true,
      aceitaFgts: true,
      aceitaConsorcio: true,
      elegivelMcmv: false,
      destaque: false,
      novo: false,
      oportunidade: true,
      rankingScore: 79,
      endereco: 'Rua [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60740-000',
      latitude: -3.7720,
      longitude: -38.5620,
      construtoraNome: null,
      diferenciais: ['Aceita FGTS', 'Aceita Financiamento', 'Próximo ao Metrô'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'parangaba',
    },
    {
      slug: 'sala-comercial-aldeota-centro-empresarial',
      titulo: 'Sala Comercial 50m² na Aldeota, Centro Empresarial',
      descricao: '[DADO_REAL_A_IMPORTAR] Sala comercial em edifício empresarial na Aldeota. Ideal para escritórios, consultórios e clínicas. Recepção, estacionamento e segurança 24h.',
      tipo: 'COMERCIAL' as const,
      modalidade: 'VENDA' as const,
      status: 'DISPONIVEL' as const,
      preco: 480000,
      precoCondominio: 1200,
      precoIptu: 1800,
      areaTotal: 50,
      areaPrivativa: 48,
      quartos: 0,
      suites: 0,
      banheiros: 1,
      vagas: 2,
      andarPavimento: 9,
      totalAndares: 15,
      anoConstrucao: 2018,
      aceitaFinanciamento: true,
      aceitaFgts: false,
      aceitaConsorcio: true,
      elegivelMcmv: false,
      destaque: false,
      novo: false,
      oportunidade: false,
      rankingScore: 58,
      endereco: 'Av. [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60150-000',
      latitude: -3.7450,
      longitude: -38.5010,
      construtoraNome: null,
      diferenciais: ['Estacionamento', 'Portaria 24h', 'Recepção', 'Internet Fibra'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'aldeota',
    },
    {
      slug: 'apartamento-2-quartos-meireles-locacao-temporada',
      titulo: 'Apartamento 2 Quartos no Meireles para Locação',
      descricao: '[DADO_REAL_A_IMPORTAR] Apartamento moderno no Meireles disponível para locação. Decoração contemporânea, todo equipado. Excelente para moradia de executivos ou temporada.',
      tipo: 'APARTAMENTO' as const,
      modalidade: 'LOCACAO' as const,
      status: 'DISPONIVEL' as const,
      preco: 4500,
      precoCondominio: 1400,
      precoIptu: 3600,
      areaTotal: 90,
      areaPrivativa: 80,
      quartos: 2,
      suites: 2,
      banheiros: 2,
      vagas: 1,
      andarPavimento: 14,
      totalAndares: 18,
      anoConstrucao: 2023,
      aceitaFinanciamento: false,
      aceitaFgts: false,
      aceitaConsorcio: false,
      elegivelMcmv: false,
      destaque: true,
      novo: true,
      oportunidade: false,
      rankingScore: 74,
      endereco: 'Av. [DADO_REAL_A_IMPORTAR]',
      numero: '[DADO_REAL_A_IMPORTAR]',
      cep: '60165-000',
      latitude: -3.7278,
      longitude: -38.4901,
      construtoraNome: null,
      diferenciais: ['Mobiliado', 'Piscina', 'Academia', 'Vista Mar', 'Novo'],
      fotos: [{ url: '[FOTO_IMOVEL_A_IMPORTAR]', ordem: 1, tipo: 'capa' }],
      fonteImportacao: 'seed_demo',
      bairroSlug: 'meireles',
    },
  ]

  for (const imovel of imoveisData) {
    const { bairroSlug, ...imovelData } = imovel
    const bairroId = bairros[bairroSlug]?.id
    if (!bairroId) {
      console.warn(`⚠️  Bairro não encontrado: ${bairroSlug}`)
      continue
    }
    await prisma.imovel.upsert({
      where: { slug: imovelData.slug },
      update: {},
      create: {
        ...imovelData,
        preco: imovelData.preco,
        precoCondominio: imovelData.precoCondominio ?? undefined,
        precoIptu: imovelData.precoIptu ?? undefined,
        areaTotal: imovelData.areaTotal,
        areaPrivativa: imovelData.areaPrivativa ?? undefined,
        rankingScore: imovelData.rankingScore ?? undefined,
        latitude: imovelData.latitude ?? undefined,
        longitude: imovelData.longitude ?? undefined,
        fotos: imovelData.fotos,
        bairroId,
        cidadeId: fortaleza.id,
        publicadoAt: new Date(),
      },
    })
  }
  console.log('✅ Imóveis criados')

  // Usuário admin padrão
  const senhaHash = await bcrypt.hash('imov@admin2024', 10)
  await prisma.user.upsert({
    where: { email: 'admin@imovimobiliaria.com.br' },
    update: {},
    create: {
      nome: 'Administrador IMOV',
      email: 'admin@imovimobiliaria.com.br',
      senhaHash,
      role: 'ADMIN',
    },
  })
  console.log('✅ Usuário admin criado (admin@imovimobiliaria.com.br / imov@admin2024)')

  // Artigos de exemplo
  const artigos = [
    {
      slug: 'como-usar-fgts-para-comprar-imovel',
      titulo: 'Como Usar o FGTS para Comprar seu Imóvel',
      subtitulo: 'Guia completo sobre as regras, limites e procedimentos para usar o FGTS na compra do seu primeiro imóvel',
      conteudo: '[CONTEUDO_REAL_A_IMPORTAR] Este artigo explica como usar o FGTS para comprar imóvel em Fortaleza.',
      categoria: 'FINANCIAMENTO' as const,
      tags: ['FGTS', 'financiamento', 'primeiro imóvel', 'Caixa Econômica'],
      tempoLeituraMinutos: 8,
      publicado: true,
      publicadoAt: new Date(),
      metaTitle: 'Como Usar o FGTS para Comprar Imóvel em Fortaleza | Guia IMOV',
      metaDescription: 'Tudo sobre o uso do FGTS na compra de imóvel: regras, documentos necessários, limites e passo a passo completo. Guia atualizado 2024.',
    },
    {
      slug: 'minha-casa-minha-vida-fortaleza-guia-completo',
      titulo: 'Minha Casa Minha Vida em Fortaleza: Guia Completo 2024',
      subtitulo: 'Tudo sobre o programa habitacional, faixas de renda, bairros disponíveis e como se inscrever em Fortaleza',
      conteudo: '[CONTEUDO_REAL_A_IMPORTAR] Guia completo sobre o Minha Casa Minha Vida em Fortaleza.',
      categoria: 'MCMV' as const,
      tags: ['MCMV', 'Minha Casa Minha Vida', 'habitação popular', 'Fortaleza', 'Caixa'],
      tempoLeituraMinutos: 12,
      publicado: true,
      publicadoAt: new Date(),
      metaTitle: 'Minha Casa Minha Vida em Fortaleza 2024 — Guia Completo | IMOV',
      metaDescription: 'Como se inscrever no MCMV em Fortaleza, faixas de renda, bairros e empreendimentos disponíveis. Guia atualizado com todas as regras do programa.',
    },
    {
      slug: 'valorizar-imovel-fortaleza-bairros-crescimento',
      titulo: 'Bairros de Fortaleza com Maior Valorização em 2024',
      subtitulo: 'Análise dos bairros com maior potencial de crescimento e valorização imobiliária na capital cearense',
      conteudo: '[CONTEUDO_REAL_A_IMPORTAR] Análise dos bairros com maior valorização em Fortaleza.',
      categoria: 'MERCADO' as const,
      tags: ['valorização', 'investimento', 'bairros', 'Fortaleza', 'mercado imobiliário'],
      tempoLeituraMinutos: 6,
      publicado: true,
      publicadoAt: new Date(),
      metaTitle: 'Bairros com Maior Valorização em Fortaleza 2024 | IMOV Imobiliária',
      metaDescription: 'Ranking dos bairros de Fortaleza com maior valorização imobiliária. Dados de preço por m², tendências e análise de mercado para investidores.',
    },
  ]

  for (const artigo of artigos) {
    await prisma.artigo.upsert({
      where: { slug: artigo.slug },
      update: {},
      create: artigo,
    })
  }
  console.log('✅ Artigos criados')

  console.log('\n🎉 Seed concluído com sucesso!')
  console.log('📊 Resumo:')
  console.log('   - 5 cidades (Fortaleza, Caucaia, Maracanaú, Eusébio, Aquiraz)')
  console.log('   - 10 bairros de Fortaleza com dados reais de mercado')
  console.log('   - 15 imóveis placeholder (fonteImportacao: seed_demo)')
  console.log('   - 3 artigos de exemplo')
  console.log('   - 1 usuário admin (admin@imovimobiliaria.com.br / imov@admin2024)')
}

main()
  .catch((e) => {
    console.error('❌ Erro no seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
