import { z } from 'zod'

export const imovelFiltrosSchema = z.object({
  tipo: z.enum(['APARTAMENTO', 'CASA', 'TERRENO', 'COBERTURA', 'COMERCIAL', 'KITNET']).optional(),
  modalidade: z.enum(['VENDA', 'LOCACAO', 'LANCAMENTO']).optional(),
  status: z.enum(['DISPONIVEL', 'VENDIDO', 'ALUGADO', 'RESERVADO', 'INATIVO']).optional(),
  bairroSlug: z.string().optional(),
  cidadeSlug: z.string().optional(),
  quartos: z.coerce.number().int().min(0).optional(),
  quartosMin: z.coerce.number().int().min(0).optional(),
  precoMin: z.coerce.number().min(0).optional(),
  precoMax: z.coerce.number().min(0).optional(),
  aceitaFinanciamento: z.coerce.boolean().optional(),
  aceitaFgts: z.coerce.boolean().optional(),
  elegivelMcmv: z.coerce.boolean().optional(),
  novo: z.coerce.boolean().optional(),
  destaque: z.coerce.boolean().optional(),
  oportunidade: z.coerce.boolean().optional(),
  construtora: z.string().optional(),
  ordenar: z.enum(['preco_asc', 'preco_desc', 'mais_recente', 'ranking']).optional(),
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
})

export const createImovelSchema = z.object({
  slug: z.string().min(3).optional(),
  titulo: z.string().min(5).max(200),
  descricao: z.string().default(''),
  tipo: z.enum(['APARTAMENTO', 'CASA', 'TERRENO', 'COBERTURA', 'COMERCIAL', 'KITNET']),
  modalidade: z.enum(['VENDA', 'LOCACAO', 'LANCAMENTO']).default('VENDA'),
  status: z.enum(['DISPONIVEL', 'VENDIDO', 'ALUGADO', 'RESERVADO', 'INATIVO']).default('DISPONIVEL'),
  preco: z.number().positive(),
  precoCondominio: z.number().optional(),
  precoIptu: z.number().optional(),
  areaTotal: z.number().positive(),
  areaPrivativa: z.number().optional(),
  quartos: z.number().int().min(0).default(0),
  suites: z.number().int().min(0).default(0),
  banheiros: z.number().int().min(0).default(1),
  vagas: z.number().int().min(0).default(0),
  andarPavimento: z.number().int().optional(),
  totalAndares: z.number().int().optional(),
  anoConstrucao: z.number().int().min(1900).max(2030).optional(),
  aceitaFinanciamento: z.boolean().default(true),
  aceitaFgts: z.boolean().default(false),
  aceitaConsorcio: z.boolean().default(false),
  elegivelMcmv: z.boolean().default(false),
  novo: z.boolean().default(false),
  destaque: z.boolean().default(false),
  oportunidade: z.boolean().default(false),
  endereco: z.string().min(3),
  numero: z.string().default('S/N'),
  complemento: z.string().optional(),
  cep: z.string().optional(),
  bairroId: z.string().uuid(),
  cidadeId: z.string().uuid(),
  empreendimentoId: z.string().uuid().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
  construtoraNome: z.string().optional(),
  diferenciais: z.array(z.string()).default([]),
  fotos: z.array(z.object({
    url: z.string(),
    legenda: z.string().optional(),
    ordem: z.number().int(),
    tipo: z.enum(['capa', 'interior', 'fachada', 'planta']),
  })).default([]),
  videoUrl: z.string().url().optional(),
  tourVirtualUrl: z.string().url().optional(),
  metaTitle: z.string().max(70).optional(),
  metaDescription: z.string().max(160).optional(),
  fonteImportacao: z.string().optional(),
})

export type ImovelFiltros = z.infer<typeof imovelFiltrosSchema>
export type CreateImovelInput = z.infer<typeof createImovelSchema>
